# Score.dev specification for testing-again Frontend
apiVersion: score.dev/v1b1
kind: Workload

metadata:
  name: testing-again-frontend

spec:
  containers:
    frontend:
      image: testing-again/frontend:latest
      variables:
        NODE_ENV: "production"
      ports:
        - port: 3000
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"

  service:
    ports:
      web:
        port: 3000
        targetPort: 3000
        protocol: TCP
